### ISSUE TITLE
Package selection uses only the first letter of package name

### ISSUE THREAD

**Issue by necrobuffalo** [monochromicon/smpn#1]
To replicate: run `npx smpn tft` or `smpn tft` and select `tft`. https://www.npmjs.com/package/t opens in the browser instead. macOS Sierra.

**Comment by necrobuffalo** [comment]
This might actually be the worst, least complete bug report I've ever written and I am sorry.

**Comment by puregarlic** [comment]
No hard feelings. This is a very strange behaviour, because as far as I can tell, I'm piping the returned values from the NPMS API straight to `open`. I'll try to see what's up.

**Comment by necrobuffalo** [comment]
Replicated it on debian stretch last night, too, after I manually fixed the shebang.

**Comment by puregarlic** [comment]
Alright, fixed the issue. Seems like it had something to do with the way my tagged template literal was processing the selected package, butchering the name when it does its second request. Just `npm install` it again, and everything should work as expected. The shebang should also be working now, I fixed it in #2 .
